# # extensions:
# #   health_check:
# #   pprof:
# #     endpoint: "0.0.0.0:1777"
# #   zpages:
# #     endpoint: "0.0.0.0:55679"

# receivers:
#   otlp:
#     protocols:
#       grpc:
#         endpoint: 0.0.0.0:4317
#       http:
#         endpoint: 0.0.0.0:4318
#   syslog:
#     tcp:
#       listen_address: 0.0.0.0:54526
#     protocol: rfc5424
#     location: UTC
#     operators:
#       - type: move
#         from: attributes.message
#         to: body
#         mapping:
#           severity: attributes.severity
#           facility: attributes.facility
#           version: attributes.version
#           timestamp: attributes.timestamp
#           hostname: attributes.host
#           appname: attributes.app
#           procid: attributes.proc_id
#           msgid: attributes.msg_id
#           structured_data: attributes.structured_data

# processors:
#   batch:

# exporters:
#   debug:
#     verbosity: detailed

# service:
#   pipelines:
#     # traces:
#     #   receivers: [otlp]
#     #   processors: [batch]
#     #   exporters: [debug]

#     # metrics:
#     #   receivers: [otlp]
#     #   processors: [batch]
#     #   exporters: [debug]

#     logs:
#       receivers: [otlp, syslog]
#       processors: [batch]
#       exporters: [debug]



# receivers:
#   otlp:
#     protocols:
#       http:
#         endpoint: "0.0.0.0:4318"
#       grpc:
#         endpoint: "0.0.0.0:4317"

#   syslog:
#     tcp:
#       listen_address: "0.0.0.0:514"
#     protocol: rfc5424
#     operators:
#       - type: syslog_parser
#         protocol: rfc5424
#         parse_from: body
#         parse_to: attributes
#       - type: remove
#         field: attributes #.unused_field  # Specify the field to remove

# processors:
#   batch:
#     timeout: 1s
#     send_batch_size: 1024

# exporters:
#   debug:
#     verbosity: detailed

# service:
#   pipelines:
#     logs:
#       receivers: [otlp, syslog]
#       processors: [batch]
#       exporters: [debug]


receivers:
  syslog:
    tcp:
      listen_address: "0.0.0.0:514"  # Listening on TCP port 514 for Syslog
    protocol: rfc5424  # RFC5424 format
    operators:
      - type: syslog_parser
        protocol: rfc5424
        parse_from: body          # Parse the body of the Syslog message
        parse_to: attributes     # Store parsed information as attributes
        preserve_to: attributes.original_message  # Preserve the original message

exporters:
  debug:
    verbosity: detailed  # Detailed logging for debugging

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

service:
  pipelines:
    logs:
      receivers: [syslog]  # Receiver to collect Syslog logs
      processors: [batch]   # Optional: Batch processor
      exporters: [debug]    # Send to debug exporter
